config/routes.rb
Toru::Application.routes.draw do

  match '/help' => 'static#generic'
  get "home/index"

  devise_for :users

  root :to => "home#index"

  resources :groups do
    resources :profiles
    resources :posts
    resources :events
    resources :items
  end
  

  
  
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/calendar.rb
class Calendar < ActiveRecord::Base
  belongs_to :group
  attr_accessible :date, :ends_at, :info, :location, :room_number, :starts_at
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  attr_accessible :body, :commenter
end

app/models/event.rb
class Event < ActiveRecord::Base
	validates :date, :presence => true
 	belongs_to :group
 	attr_accessible :date, :ends_at, :info, :location, :room_number, :starts_at

end

app/models/group.rb
class Group < ActiveRecord::Base
  attr_accessible :affiliation, :group_name, :group_type

  validates :group_name, :presence => true

  has_many :users  
  has_many :posts, :dependent => :destroy
  has_many :events, :dependent => :destroy
  has_many :items, :dependent => :destroy
  has_one :profile, :dependent => :destroy
 
end

app/models/group_profile.rb
class GroupProfile < ActiveRecord::Base
  belongs_to :group
  attr_accessible  :group_mission, :text_block_body, :text_block_content
end

app/models/item.rb
class Item < ActiveRecord::Base
	validates :header, :presence => true
	belongs_to :group
	attr_accessible :description, :header, :url
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :body, :posted_by, :posted_by_uid, :post_id

  validates :body, :presence => true

  belongs_to :group

end

# has "group_id" for posts access

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :group
  attr_accessible  :group_mission, :text_block_body, :text_block_content
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name, :surname
  # attr_accessible :title, :body
  has_many :groups


end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  layout "group" , :except => [:index, :new]
  before_filter :authenticate_user!
 
  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @groups }
    end
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    @group = Group.find(params[:id])
    @post = Post.new
    @post.group = @group
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @group }
    end
  end

  # GET /groups/new
  # GET /groups/new.json
  def new
    @group = Group.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @group }
    end
  end

  # GET /groups/1/edit
  def edit
    @group = Group.find(params[:id])

  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(params[:group])
    @group.profile = Profile.new
    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render json: @group, status: :created, location: @group }
      else
        format.html { render action: "new" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /groups/1
  # PUT /groups/1.json
  def update
    @group = Group.find(params[:id])     
    respond_to do |format|
      if @group.update_attributes(params[:group])
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group = Group.find(params[:id])
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	layout "home"	
	before_filter :redirect_if_signed_in


	def redirect_if_signed_in
		if signed_in?(:user)
			redirect_to "/groups"
		end
	end

	def index
	end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  layout "group" 
  before_filter :load_group


  public
  def load_group
    @group = Group.find(params[:group_id])
  end

  # GET /items
  # GET /items.json
  def index
    @items = @group.items.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @items }
    end
  end

  # GET /items/1
  # GET /items/1.json
  def show
    @item = @group.items.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @item }
    end
  end

  # GET /items/new
  # GET /items/new.json
  def new
    @item = @group.items.build
  end

  # GET /items/1/edit
  def edit
    @item = @group.items.find(params[:id])
  end

  # POST /items
  # POST /items.json
  def create
    @item = @group.items.build(params[:item])

    respond_to do |format|
      if @item.save
        format.html { redirect_to group_items_path(@group), notice: 'Item was successfully created.' }
        format.json { render json: @item, status: :created, location: @item }
      else
        format.html { render action: "new" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /items/1
  # PUT /items/1.json
  def update
    @item = @group.items.find(params[:item])

    respond_to do |format|
      if @item.update_attributes(:item => params[:item])
        format.html { redirect_to group_items_path, notice: 'Item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item = @group.items.find(params[:id])
    @item.destroy

    respond_to do |format|
      format.html { redirect_to group_items_path(@group) }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendars_helper.rb
module CalendarsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/groups/_form.html.erb
<%= form_for @group, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :group_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :group_name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :group_type, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :group_type, :class => 'text_field' %>
    </div>
  </div>
   
    <div class="control-group">
    <%= f.label :affiliation, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :affiliation, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                @group, :class => 'btn' %>
  </div>

  
<% end %>

app/views/groups/edit.html.erb
<%- model_class = Group -%>
<div class="page-header">
  <h1>Edit your group</h1>
</div>
<%= render :partial => 'form' %>

app/views/groups/index.html.erb
<%- model_class = Group -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:group_name) %></th>
      <th><%= model_class.human_attribute_name(:group_type) %></th>
      <th><%= model_class.human_attribute_name(:affiliation) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= link_to group.group_name, group_path(group) %></td>
        <td><%= group.group_type %></td>
        <td><%= group.affiliation %></td>
        <td><%= distance_of_time_in_words_to_now(group.created_at) %> ago</td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_group_path(group), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      group_path(group),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_group_path,
            :class => 'btn btn-primary' %>

app/views/groups/new.html.erb
<%- model_class = Group -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/groups/show.html.erb
<div style="margin-top: 20px">
	<p class="well" style="width:62%;">Share your thoughts and ideas.</p>
	<%= render "posts/form" %>
</div>
	
<div id="listing">
	<% @group.posts.each do |post| %>
		<div class="list item">
				<%= post.body %> <br />
				<small><%= link_to 'Delete', group_post_path(@group.id, post.id), :confirm => "are you sure?", :method => :delete %>
				| Posted <%= distance_of_time_in_words_to_now(post.created_at) %> ago
			</small>
		</div>
		<hr />
	<% end %>
</div>

<% content_for :events do %>
        <div class="span2 pull-right">
           Upcoming Events <hr />

			<% @group.events.take(3).each do |event| %>

			          <h5 style="margin-bottom=0px;">
			            <%= link_to event.date, group_event_path(@group.id, event.id) %> <br />
			          </h5>
			 
			          <%= Time.parse(event.starts_at).strftime("%I:%M %p")  %> -
			          <%= Time.parse(event.ends_at).strftime("%I:%M %p")  %>
			          <%= event.location  %>,
			          <%= event.room_number  %> <br/>
			 		  <hr />


			<% end %>
          <%= link_to 'View group calendar', group_events_path(@group) %>
        </div><!--/span-->

<% end %>