config/routes.rb
Toru::Application.routes.draw do

  match '/help' => 'static#generic'
  get "home/index"

  devise_for :users

  root :to => "home#index"

  resources :groups do
    resources :profiles
    resources :posts
    resources :events
    resources :items
  end
  

  
  
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/calendar.rb
class Calendar < ActiveRecord::Base
  belongs_to :group
  attr_accessible :date, :ends_at, :info, :location, :room_number, :starts_at
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  attr_accessible :body, :commenter
end

app/models/event.rb
class Event < ActiveRecord::Base
	validates :date, :presence => true
 	belongs_to :group
 	attr_accessible :date, :ends_at, :info, :location, :room_number, :starts_at

end

app/models/group.rb
class Group < ActiveRecord::Base
  attr_accessible :affiliation, :group_name, :group_type

  validates :group_name, :presence => true

  has_many :users  
  has_many :posts, :dependent => :destroy
  has_many :events, :dependent => :destroy
  has_many :items, :dependent => :destroy
  has_one :profile, :dependent => :destroy
 
end

app/models/group_profile.rb
class GroupProfile < ActiveRecord::Base
  belongs_to :group
  attr_accessible  :group_mission, :text_block_body, :text_block_content
end

app/models/item.rb
class Item < ActiveRecord::Base
	validates :header, :presence => true
	belongs_to :group
	attr_accessible :description, :header, :url
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :body, :posted_by, :posted_by_uid, :post_id

  validates :body, :presence => true

  belongs_to :group

end

# has "group_id" for posts access

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :group
  attr_accessible  :group_mission, :text_block_body, :text_block_content
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name, :surname
  # attr_accessible :title, :body
  has_many :groups


end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  layout "group" 
  before_filter :load_group


  public
  def load_group
    @group = Group.find(params[:group_id])
  end
  
  # GET /events
  # GET /events.json
  def index
    @events = @group.events.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @events }
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = @group.events.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/new
  # GET /events/new.json
  def new
    @event = @group.events.build
  end

  # GET /events/1/edit
  def edit
    @event = @group.events.find(params[:id])
  end

  # POST /events
  # POST /events.json
  def create
    @event = @group.events.build(params[:event])

    respond_to do |format|
      if @event.save
        format.html { redirect_to group_events_path(@group), notice: 'Event was successfully created.' }
        format.json { render json: @event, status: :created, location: @event }
      else
        format.html { render action: "new" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.json
  def update
    @event = @group.events.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to group_events_path(@group), notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = @group.events.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to group_events_path(@group) }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	layout "home"	
	before_filter :redirect_if_signed_in


	def redirect_if_signed_in
		if signed_in?(:user)
			redirect_to "/groups"
		end
	end

	def index
	end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  layout "group" 
  before_filter :load_group


  public
  def load_group
    @group = Group.find(params[:group_id])
  end

  # GET /items
  # GET /items.json
  def index
    @items = @group.items.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @items }
    end
  end

  # GET /items/1
  # GET /items/1.json
  def show
    @item = @group.items.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @item }
    end
  end

  # GET /items/new
  # GET /items/new.json
  def new
    @item = @group.items.build
  end

  # GET /items/1/edit
  def edit
    @item = @group.items.find(params[:id])
  end

  # POST /items
  # POST /items.json
  def create
    @item = @group.items.build(params[:item])

    respond_to do |format|
      if @item.save
        format.html { redirect_to group_items_path(@group), notice: 'Item was successfully created.' }
        format.json { render json: @item, status: :created, location: @item }
      else
        format.html { render action: "new" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /items/1
  # PUT /items/1.json
  def update
    @item = @group.items.find(params[:item])

    respond_to do |format|
      if @item.update_attributes(:item => params[:item])
        format.html { redirect_to group_items_path, notice: 'Item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item = @group.items.find(params[:id])
    @item.destroy

    respond_to do |format|
      format.html { redirect_to group_items_path(@group) }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendars_helper.rb
module CalendarsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/events/_form.html.erb
<%= simple_form_for([@group, @event], {:class => "form-vertical"}) do |f| %>
<%= f.error_notification %>

  <div class="form-inputs">
  <label>Date</label>
  	<%= f.text_field :date, :class => "datepicker"  %> <br/>
  	<%= f.input :starts_at, :wrapper_html => { :class => 'span4' }  %>
  	<%= f.input :ends_at, :wrapper_html => { :class => 'span5' }  %>  <br/>
  	<%= f.input :location, :wrapper_html => { :class => 'span4' }, :class => 'text_field' %>
  	<%= f.input :room_number,:wrapper_html => { :class => 'span4' }, :class => 'text_field' %>
  	<%= f.text_area :info, :wrapper_html => { :class => 'span8' },  :class => 'text_field' %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>

<% end %>

<script type="text/javascript">
$('.datepicker').datepicker({format: 'dd-MM-yyyy'});
</script>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @group_event %> |
<%= link_to 'Back', group_events_path %>

app/views/events/index.html.erb
<div style="margin-top: 30px">
<%= link_to 'New Event', new_group_event_path, :class => "btn btn-primary", id: "new_link", remote: true %>
</h3>
<hr />
</div>

<h1>Listing events</h1> <br />

      <% @group.events.each do |event| %>

          <h4 style="margin-bottom=0px;">
            <%= link_to event.date, group_event_path(@group.id, event.id) %> <br />
          </h4>
 
          <%= Time.parse(event.starts_at).strftime("%I:%M %p")  %> -
          <%= Time.parse(event.ends_at).strftime("%I:%M %p")  %>
          <%= event.location  %>,
          <%= event.room_number  %> <br/>
          <p><%= event.info  %></p>

          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      group_event_path(@group.id, event.id),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
    <hr />


    <% end %>

<br />

<script type="text/javascript">
  $('[data-behaviour~=datepicker]').datepicker()
</script>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', group_events_path %>

app/views/events/new.js.erb
$('#new_link').hide().after('<%= j render("form") %> ');

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<h4 style="margin-bottom=0px;"><%= @event.date %></h4> 
<%= Time.parse(@event.starts_at).strftime("%I:%M %p")  %> -
<%= Time.parse(@event.ends_at).strftime("%I:%M %p")  %> <br/>
<%= @event.location  %>,
<%= @event.room_number  %> <br/>
<p><%= @event.info  %></p>


<%= link_to 'Back', group_events_path %>