config/routes.rb
Toru::Application.routes.draw do

  match '/help' => 'static#generic'
  get "home/index"

  devise_for :users

  root :to => "home#index"

  resources :groups do
    resources :profiles
    resources :posts
    resources :events
    resources :items
  end
  

  
  
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/calendar.rb
class Calendar < ActiveRecord::Base
  belongs_to :group
  attr_accessible :date, :ends_at, :info, :location, :room_number, :starts_at
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  attr_accessible :body, :commenter
end

app/models/event.rb
class Event < ActiveRecord::Base
	validates :date, :presence => true
 	belongs_to :group
 	attr_accessible :date, :ends_at, :info, :location, :room_number, :starts_at

end

app/models/group.rb
class Group < ActiveRecord::Base
  attr_accessible :affiliation, :group_name, :group_type

  validates :group_name, :presence => true

  has_many :users  
  has_many :posts, :dependent => :destroy
  has_many :events, :dependent => :destroy
  has_many :items, :dependent => :destroy
  has_one :profile, :dependent => :destroy
 
end

app/models/group_profile.rb
class GroupProfile < ActiveRecord::Base
  belongs_to :group
  attr_accessible  :group_mission, :text_block_body, :text_block_content
end

app/models/item.rb
class Item < ActiveRecord::Base
	validates :header, :presence => true
	belongs_to :group
	attr_accessible :description, :header, :url
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :body, :posted_by, :posted_by_uid, :post_id

  validates :body, :presence => true

  belongs_to :group

end

# has "group_id" for posts access

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :group
  attr_accessible  :group_mission, :text_block_body, :text_block_content
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name, :surname
  # attr_accessible :title, :body
  has_many :groups


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	layout "home"	
	before_filter :redirect_if_signed_in


	def redirect_if_signed_in
		if signed_in?(:user)
			redirect_to "/groups"
		end
	end

	def index
	end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  layout "group" 
  before_filter :load_group


  public
  def load_group
    @group = Group.find(params[:group_id])
  end

  # GET /items
  # GET /items.json
  def index
    @items = @group.items.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @items }
    end
  end

  # GET /items/1
  # GET /items/1.json
  def show
    @item = @group.items.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @item }
    end
  end

  # GET /items/new
  # GET /items/new.json
  def new
    @item = @group.items.build
  end

  # GET /items/1/edit
  def edit
    @item = @group.items.find(params[:id])
  end

  # POST /items
  # POST /items.json
  def create
    @item = @group.items.build(params[:item])

    respond_to do |format|
      if @item.save
        format.html { redirect_to group_items_path(@group), notice: 'Item was successfully created.' }
        format.json { render json: @item, status: :created, location: @item }
      else
        format.html { render action: "new" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /items/1
  # PUT /items/1.json
  def update
    @item = @group.items.find(params[:item])

    respond_to do |format|
      if @item.update_attributes(:item => params[:item])
        format.html { redirect_to group_items_path, notice: 'Item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item = @group.items.find(params[:id])
    @item.destroy

    respond_to do |format|
      format.html { redirect_to group_items_path(@group) }
      format.json { head :no_content }
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :load_group


  public
  def load_group
    @group = Group.find(params[:group_id])
  end
  

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = @group.posts.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = @group.posts.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end


  # POST /posts
  # POST /posts.json
  def create
    @post = @group.posts.build(params[:post])


    respond_to do |format|
      if @post.save
        format.html { redirect_to group_path(@post.group), notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    group = Group.find(params[:group_id])
    post_to_delete = group.posts.find{|g| g.id == params[:id].to_i }
    post_to_delete.destroy
    respond_to do |format|
      format.html { redirect_to group_path(@group) }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendars_helper.rb
module CalendarsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/items/_form.html.erb
<%= simple_form_for([@group, @item]) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  	<%= f.input :header, :class => 'text_field' %>
  	<%= f.input :url, :class => 'text_field' %>
  	<%= f.text_area :description, :class => 'text_field' %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render 'form' %>

<%= link_to 'Show', @group_item %> |
<%= link_to 'Back', group_items_path %>

app/views/items/index.html.erb
<div style="margin-top: 30px">
<%= link_to 'Add to library', new_group_item_path, :class => "btn btn-primary", id: "new_link", remote: true %>
</h3>
<hr />
</div>

<h1>Listing items</h1>

      <% @group.items.each do |item| %>
      <ul class="thumbnails">
        <li class="span4">
          <div class="thumbnail">
           <h3> <%= link_to item.header, item.url, :target => "_blank"  %></h3>
           <p><%= item.description %></p> <br />
                     <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      group_item_path(@group.id, item.id),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
          </div>
        </li>



    <% end %>

</div>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render 'form' %>

<%= link_to 'Back', group_items_path %>

app/views/items/new.js.erb
$('#new_link').hide().after('<%= j render("form") %> ');

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to @item.header, @item.url, :target => "_blank"  %> <br />
<%= @item.description %> <br />

<%= link_to 'Back', group_items_path %>

app/views/posts/_form.html.erb
<%= form_for([@group, @post]) do |f| %>
	<div style="posts">
		<%= f.text_area :body, :class => 'text_field' %>
	</div>

	<div>
   		<%= f.submit nil, :class => 'btn btn-primary' %>
	</div>

<% end %>

app/views/posts/_post.html.erb
<%= post.body %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <tr>
    <th>Body</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @posts.each do |post| %>
  <tr>
    <td><%= post.body %></td>
    <td><%= post.posted_by %></td>
    <td><%= link_to 'Show', post %></td>
    <td><%= link_to 'Edit', edit_post_path(post) %></td>
    <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
	<b> Content </b>
	<%= @post.body %>
</p>


<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>
	