config/routes.rb
Toru::Application.routes.draw do

  match '/help' => 'static#generic'
  get "home/index"

  devise_for :users

  root :to => "home#index"

  resources :groups do
    resources :profiles
    resources :posts
    resources :events
    resources :items
  end
  

  
  
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/calendar.rb
class Calendar < ActiveRecord::Base
  belongs_to :group
  attr_accessible :date, :ends_at, :info, :location, :room_number, :starts_at
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  attr_accessible :body, :commenter
end

app/models/event.rb
class Event < ActiveRecord::Base
	validates :date, :presence => true
 	belongs_to :group
 	attr_accessible :date, :ends_at, :info, :location, :room_number, :starts_at

end

app/models/group.rb
class Group < ActiveRecord::Base
  attr_accessible :affiliation, :group_name, :group_type

  validates :group_name, :presence => true

  has_many :users  
  has_many :posts, :dependent => :destroy
  has_many :events, :dependent => :destroy
  has_many :items, :dependent => :destroy
  has_one :profile, :dependent => :destroy
 
end

app/models/group_profile.rb
class GroupProfile < ActiveRecord::Base
  belongs_to :group
  attr_accessible  :group_mission, :text_block_body, :text_block_content
end

app/models/item.rb
class Item < ActiveRecord::Base
	validates :header, :presence => true
	belongs_to :group
	attr_accessible :description, :header, :url
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :body, :posted_by, :posted_by_uid, :post_id

  validates :body, :presence => true

  belongs_to :group

end

# has "group_id" for posts access

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :group
  attr_accessible  :group_mission, :text_block_body, :text_block_content
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name, :surname
  # attr_accessible :title, :body
  has_many :groups


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendars_helper.rb
module CalendarsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Toru" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body class="container">

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Toru</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav pull-right">
              <li><%= link_to "Groups", groups_path  %></li>
              <li><%= link_to "Help", help_path  %></li>
              <ul class="nav pull-right">
              <li class="dropdown">
              <a href="#"  
                class="dropdown-toggle"  
                data-toggle="dropdown">  
                Me  
                <b class="caret"></b>  
              </a> 
              <ul class="dropdown-menu">
              <li><%= link_to ' Settings ', edit_user_registration_path %> </a></li>
              <li> <%= link_to 'Sign out', destroy_user_session_path, method: :delete %></a></li>
            </ul>
            </ul>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

        <div class="page-header span9">
    <h1>Hello, <%= current_user.name %> <small><%= link_to ' View and edit your profile ', edit_user_registration_path %> </small></h1>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span2">
         
        </div><!--/span-->
        <div class="span9 table-hover">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer class="navbar-fixed-bottom">
        <p>&copy; Ulukman Karabukaev 2013</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Toru" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body class="container">

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Toru</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav pull-right">
              <li><%= link_to "Groups", groups_path  %></li>
              <li><%= link_to "Help", help_path  %></li>
              <ul class="nav pull-right">
              <li><%= link_to 'Login ', new_user_session_path %> </a></li>
              </ul>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

        <div class="page-header span9">


    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span2">
         
        </div><!--/span-->
        <div class="span9 table-hover">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer class="navbar-fixed-bottom">
        <p>&copy; Ulukman Karabukaev 2013</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/layouts/group.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Toru" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body class="container">

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Toru</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav pull-right">
              <li><%= link_to "Groups", groups_path  %></li>
              <li><%= link_to "Help", help_path %></li>
              <ul class="nav">
                <li class="dropdown">
                  <a href="#"  
                    class="dropdown-toggle"  
                    data-toggle="dropdown">  
                    Me  
                    <b class="caret"></b>  
                  </a> 
                  <ul class="dropdown-menu">
                    <li><%= link_to ' Settings ', edit_user_registration_path %> </a></li>
                    <li> <%= link_to 'Sign out', destroy_user_session_path, method: :delete %></a></li>
                  </ul>
                </li>
              </ul>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div id="user_nav" class="pull-right" style="display:none">
        <% if user_signed_in? %>
            Signed in as <%= current_user.email %>. 
            <%= link_to 'Sign out', destroy_user_session_path, method: :delete %>
        <% else %>
            <%= link_to 'Register', new_user_registration_path %> or <%= link_to 'Sign in', new_user_session_path %>
        <% end %>
    </div>

    <div class="page-header">
      <h1><%= @group.group_name %><br/> <small><%= @group.group_type %> | Created <%= distance_of_time_in_words_to_now(@group.created_at) %> ago</small></h1>
    </div>

    <div class="container-fluid" style="padding-left: 0px;">
      <div class="row-fluid">
        <div class="span2">
          <div class="sidebar-nav">
            <ul class="nav nav-list" style="padding-left: 0px;">
              <li><h3><%= link_to "Discussion", @group %></h3></li>
              <li><h3><%= link_to "Calendar", group_events_path(@group) %></h3></li>
               <li><h3><%= link_to "Library", group_items_path(@group)  %></h3></li>
                <li><h3><%= link_to "Info", edit_group_profile_path(@group, @group.profile)  %></h3></li>
                 <li><h3><%= link_to "Settings", edit_group_path(@group) %></h3></li>
            </ul>
          </div><!--/.sidebar-nav -->
        </div><!--/span-->
        <div class="span8">
          <%= bootstrap_flash %>
          <%= yield %>
        </div><!--/span-->
        
        <% if content_for?(:events) %>
          <div><%= yield(:events) %></div>
        <% end %>     


        </div><!--/row-->
      </div><!--/container-->




      <footer class="navbar-fixed-bottom">
        <p>&copy; Ulukman Karabukaev 2013</p>
      </footer>


    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Toru" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

   
  <div class="header-wrapper">
    <div class="header offset2">
      <h3> Toru </h3>
      <h5 style="color:red;"><%= link_to 'Login', new_user_session_path %></h5>
    </div>

    <div class="container-fluid">
        <div class="span12 home">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
    </div><!--/container-->
    <div style="clear:both;"></div>
    <div class="gradient-wrapper"> 
      <ul class="inline" id="group-types">
        <li> 
          <img src="assets/groups-types-02.png">
          <h4>Academic Clubs</h4>
          <ul class="unstyled">
            <li>Chess club</li>
            <li>Young Democrats</li>
            <li>Model U.N.</li>
          </ul>
        </li>
        <li> 
          <img src="assets/groups-types-01.png">
          <h4>Group Projects</h4>
          <ul class="unstyled">
            <li>Skyscraper mockup</li>
            <li>Spanish Presentation</li>
            <li>Case competition</li>
          </ul>
        </li>
        <li>
          <img src="assets/groups-types-03.png">
          <h4>Study Groups</h4>
          <ul class="unstyled">
            <li>Midterm prep</li>
            <li>Calculus problem set</li>
            <li>Pushkin analysis</li>
          </ul>
        </li>
        <li>  
          <img src="assets/groups-types-04.png">
          <h4>Common Interests</h4>
          <ul class="unstyled">
            <li>Explorers Club</li>
            <li>Typophiles</li>
            <li>Economics department</li>
          </ul>
        </li>
        <div style="clear:both;"></div>
      </ul>
    </div>
  </div> <!--/header-wrapper-->

  <div id="screenshot-strip">
    <ul class="inline" id="screenshots">
      <li style=""> 
        <img src="assets/groups-screenshot-01.jpg">
        <h4> Timeline </h4>
        <p> See discussions, upcoming events, and assignments in a unified feed. </p>
      </li>
      <li style="margin-left:20px; margin-right:20px;">
        <img src="assets/groups-screenshot-03.jpg">
        <h4> Library </h4>
        <p> Share interesting links and articles with the group. </p>
      </li>
      <li style="">
        <img src="assets/groups-screenshot-02.jpg">
        <h4> Calendar </h4>
        <p>  Plan and discuss group events. Keep track of activity on your dashboard. </p>
      </li>
    </ul>
  </div>

  <footer class="navbar" style="text-align:center;">
    <p>&copy; Ulukman Karabukaev 2013</p>
  </footer>



    <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>